name: Comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest

    steps:
      - name: "dump github context"
        run: echo "${{ toJson(github.event) }}" | jq .
        shell: bash

      - name: "comment with action"
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multiline test comment 
            - with GitHub **markdown** :sparkles:
            - created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment

          reactions: hooray
